spring.application.name=Long-Term-Integrity

# File handling
documents.folder=src/test/resources/public/

# File upload size limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

# Raft cluster configuration
raft.group.id="integrityGroup"
raft.storage.base=/tmp/ratis
raft.peers=n0:127.0.0.1:6000,n1:127.0.0.1:6001,n2:127.0.0.1:6002

# Ethereum blockchain configuration
blockchain.rpc.url=http://localhost:8545
blockchain.contract.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
blockchain.deployer.private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# Logging levels for Raft
logging.level.org.apache.ratis=WARN
logging.level.org.apache.ratis.server=ERROR
