spring.application.name=Merkle-Trees
documents.folder=src/test/resources/public/

# File upload size limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

# Raft cluster configuration
raft.group.id=integrity-group
raft.peers=localhost:9000,localhost:9001,localhost:9002
